# Site
repository: hymn-fly/hymn-fly.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 길근오
title: Java Backend Engineer
email: rlfrmsdh1@gmail.com
# website: https://geuno.notion.site/fe38c96690c74550a704b892a801d632
# website_title: Notion

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  hymn-fly
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: rlfrmsdh
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: notion page
  icon: fas fa-globe
  url: https://geuno.notion.site/112374c6e10b486cb9659c427e7235a2
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/geuno.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm using Spring Boot for developing backend and Vue for frontend web pages. I'm enjoying learning new skills, studying consistently.
  Based on this knowledge, I usually communicate with colleague for better cooperation and making the better application.
#  Java Spring Boot를 이용한 백엔드, Vue 프론트엔드 웹 개발을 하는 길근오입니다. 서비스를 더 좋게 할 수 있는 새로운 기술들을 배워보고 공부하는 것을 좋아하고 다른 사람들과 같이 이야기하며 프로덕트를 만들어 나가는 것을 좋아합니다.
  Skillful tech stacks are <mark>Spring Boot</mark>, <mark>Vue.js</mark>, <mark>ELK Stack</mark>, <mark>AWS</mark>, <mark>Docker</mark>, <mark>MySQL</mark>
#  주요 기술 스택으로는 <mark>Spring Boot</mark>, <mark>Vue</mark>, <mark>ELK Stack</mark>, <mark>AWS</mark>, <mark>Docker</mark>, <mark>MySQL</mark>를 이용합니다.
  
  I'm trying to upgrade my tech stacks so that I can have good command of those skills.
  Nowdays, I'm doing projects to use my knowledge and skill sets.
#  현재는 가지고 있는 기술 스택을 전문가 처럼 자유자재로 활용할 수 있도록 노력하는 중입니다.
  
#  장기적으로 해당 기술 스택들을 이용해서 많은 프로덕트를 만들어보는 경험을 쌓고 싶습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Nextlab
        link: https://www.nextlab.ai/
        sub_title: Python backend & deeplearning engineer
        caption: 2018.12 ~ 2021.11
        quote: >
          Deeplearning based SI Company
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#          - 경정 청구 자동화 서비스 개발(AWS Lambda, ApiGateway, DynamoDB, SQS)
#          - 중고차 시세 제공 서비스 개발(Django, Docker, Redis, Oracle)
#          - 딥러닝을 이용한 비전 프로젝트 진행(Tensorflow, Opencv)
        description: | # this will include new lines to allow paragraphs
          - tax issue automation service(AWS Lambda, ApiGateway, DynamoDB, SQS)
          - Used-car price search WebSite development(Django, Docker, Redis, Oracle)
      - layout: left
        title: LG U+
        sub_title: Backend Developer
        caption: 2022.9 ~ 
        description: |
          - Virtual Office Login Server (Java Spring Boot)
          - Admin page for virtual-office (Vue.js)
          - Statistics Visualization (Elastic Search & Kibana)
          - CI/CD (Github action & Jenkins)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Tax Automation Service
#         link: https://www.nextlab.ai/
#         sub_title: Python 백엔드 & 딥러닝 개발자
        quote: >
          Automating accountant and tax accountant's cumbersome handworks using AWS Lambda
#          회계사, 세무사가 진행하는 번거로운 수작업들을 자동화 해주는 서비스를 AWS Lambda 기반으로 구성
        description: | # this will include new lines to allow paragraphs
            - Save already submitted forms in AWS DynamoDB
            - Some logic in AWS Lambda
            - After completion, event will be transferred to AWS SQS
      - layout: top-middle
        title: Used-car price search Website
        link : https://www.ajsellcar.co.kr/ajScore/searchNumber.do
        quote: >
          Service serving used-car price and trading statistics
        description: |
            - Developing Backend API (Django)
            - Scheduleing job (Celery)
            - Use cache to prevent long query (Redis)
            - API Security using Jwt token
      - layout: top-middle
        title: 
          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul National University
        caption: 2011.3 - 2015.8
        sub_title: Mechanical and Aerospace Engineering
        description: | # this will include new lines to allow paragraphs
          - Score : 3.65 / 4.3
          - Drone Inverted pendulum problem simulation using Matlab
      - layout: left
        title: Seoul National University Graduate School
        caption: 2015.9 - 2018.8
        sub_title: Aerospace Engineering Master Degree
        description: | # this will include new lines to allow paragraphs
          - Score : 3.95 / 4.3
          - Attitude Control simulation for drone with robotic arm
          - Design adaptive controller using Neural networks
      - layout: left
        title: Programmers Devcourse for Backend Engineering
        link: https://programmers.co.kr/learn/courses/13478
        caption: 2022.3 - 2022.8
        description: | # this will include new lines to allow paragraphs
          - Learning Spring principle(DI, IoC, AoP, Spring MVC 패턴 등)
          - Learning Spring Persistence framework (JPA, JDBC, QueryDsl, JPQL)
          - Spring Security
          - AWS, Linux
          - Code design based on TDD, OOP. Interacting Code reviews from hands-on mentors
  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend
        quote: >
#          자신 있는 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - Java, Typescript
          - Spring Boot, Spring Security, Spring Data Jpa, JDBC
          - JPA, MyBatis
          - Mysql, Redis
          - Gradle, Maven
          - IntelliJ, Visual Studio Code

      - layout: left
        title: DevOps

        description: | # this will include new lines to allow paragraphs
          - Docker, Docker Compose
          - AWS Lambda, EC2, S3, RDS
          - Linux
          - ELK Stack


#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
