# Site
repository: hymn-fly/hymn-fly.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 길근오
title: Java Backend Engineer
email: rlfrmsdh1@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  hymn-fly
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: rlfrmsdh
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: notion page
  icon: fas fa-globe
  url: https://geuno.notion.site/fe38c96690c74550a704b892a801d632
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/geuno.jpg
about_content: | # this will include new lines to allow paragraphs
  Java 백엔드 엔지니어를 준비하고 있는 길근오라고 합니다. 서울대학교 우주항공공학부 학부/대학원(비행역학제어 연구실. 석사)을 졸업하였고 그 후 전문연구요원을 웹개발 회사에서 진행하면서 백엔드 엔지니어에 대한 흥미가 생겨 직무를 전환하게 되었습니다.
  
  전문연구요원을 진행한 회사에서 웹 개발프로젝트를 진행하며 <mark>AWS</mark>(S3, Lambda, ECR, EC2, RDS 등)를 이용한 서비스를 운영하였고 python의 <mark>Django</mark>, <mark>Flask</mark> 프레임워크를 이용하여 웹개발 수행, <mark>Docker</mark> 를 이용하여 <mark>Linux</mark> 서버에 배포하였습니다.

  이후, **프로그래머스 클라우드 기반 백엔드 엔지니어링 데브코스**를 들으며, 자바 스프링 백엔드 엔지니어가 되기 위한 기초(CS, 특정 기술의 필요성 등)를 갈고 닦고 있습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 넥스트랩
        link: https://www.nextlab.ai/
        sub_title: Python 백엔드 & 딥러닝 개발자
        caption: 2018.12 ~ 2021.11
        quote: >
          딥러닝 기반 SI 기업
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          - 경정 청구 자동화 서비스 개발(AWS Lambda & CloudWatch & RDS)
          - 중고차 시세 제공 서비스 개발(Django, Docker, Redis, Oracle)
          - 딥러닝을 이용한 비전 프로젝트 진행(Tensorflow, Opencv)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 경정 청구 자동화 서비스 개발
#         link: https://www.nextlab.ai/
#         sub_title: Python 백엔드 & 딥러닝 개발자
        quote: >
          회계사, 세무사가 진행하는 번거로운 수작업들을 자동화 해주는 서비스를 AWS Lambda 기반으로 구성
        description: | # this will include new lines to allow paragraphs
            - AWS DynamoDB에 기존 신고 데이터 적재
            - 기존 신고 데이터를 통해 잘못된 신고를 수정하여 신고(AWS Lambda)
            - AWS SQS를 이용한 신고 완료 이벤트 전달
      - layout: top-middle
        title: 중고차 시세 제공 서비스 개발
        link : https://www.ajsellcar.co.kr/ajScore/searchNumber.do
        quote: >
          중고 거래 시장에서 거래되는 차량의 중고가와 중고 거래 통계를 제공해주는 서비스
        description: |
            - 시세 서비스 백엔드 API 개발
            - 정기적인 데이터 처리 Celery 로 구현
            - Redis 이용한 캐시 기능 적용
            - Jwt 토큰을 이용한 API 보안
      - layout: top-middle
        title: 
          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 서울대학교
        caption: 2011.3 - 2015.8
        sub_title: 기계항공공학부
        description: | # this will include new lines to allow paragraphs
          - 학점 : 3.65 / 4.3
          - Matlab을 활용한 드론의 역진자 제어 시뮬레이션 수행
      - layout: left
        title: 서울대학교 대학원
        caption: 2015.9 - 2018.8
        sub_title: 우주항공공학 석사
        description: | # this will include new lines to allow paragraphs
          - 학점 : 3.95 / 4.3
          - 쿼드로터(드론)에 로봇팔이 달려있는 시스템에 대한 자세 제어 시뮬레이션 수행
          - 인공신경망을 활용하여 적응 제어기 설계
      - layout: left
        title: 프로그래머스 클라우드 기반 백엔드 엔지니어링 데브코스
        link: https://programmers.co.kr/learn/courses/13478
        caption: 2022.3 - 2022.8(예정)
        description: | # this will include new lines to allow paragraphs
          - Spring의 원리 학습(DI, IoC, AoP, Spring MVC 패턴 등)
          - JPA, JDBC, QueryDsl, JPQL 등 DB 활용 기술 학습
          - Spring Security 학습
          - AWS, Linux 학습
          - TDD, OOP에 대한 개념 & 실무진 멘토의 코드리뷰를 통한 학습
  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend
        quote: >
          사용한 경험이 있는 기술들 입니다.
        description: | # this will include new lines to allow paragraphs
          - Java, Python
          - Spring Boot, Spring MVC, Spring Security, Spring Data Jpa, JDBC
          - JPA
          - Oracle, Postgresql, Mysql, Redis
          - Gradle, Maven
          - IntelliJ, Visual Studio Code

      - layout: left
        title: DevOps

        description: | # this will include new lines to allow paragraphs
          - Docker, Docker Compose
          - AWS Lambda, EC2, S3, RDS
          - Linux


#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
